In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('pipeline.csv')

In [3]:
data.head()

,Classification,EdgeOfFlightLine,GpsTime,Intensity,NumberOfReturns,OriginId,PointSourceId,ReturnNumber,ScanAngleRank,ScanDirectionFlag,UserData,X,Y,Z
0,2.0,0.0,55112.731,68.0,1.0,17583.0,79.0,1.0,0.0,1.0,70.0,447600.764,4653525.583,272.70
1,2.0,0.0,55112.731,42.0,2.0,17583.0,79.0,2.0,1.0,1.0,70.0,447604.361,4653526.231,272.80
2,2.0,0.0,55112.731,58.0,2.0,17583.0,79.0,2.0,1.0,1.0,70.0,447606.119,4653526.573,273.10
3,2.0,0.0,55112.744,48.0,2.0,17583.0,79.0,2.0,0.0,0.0,70.0,447602.543,4653526.792,272.70
4,2.0,0.0,55112.744,71.0,2.0,17583.0,79.0,2.0,0.0,0.0,70.0,447600.764,4653526.465,272.54